name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  app_name: app_${{ github.run_number }}
  
jobs:
  build:
    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Build
      run: g++ Hello_World.cpp -o ${{ env.app_name }}_${{ runner.os }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
       name: artifact
       path: ${{ env.app_name }}_${{ runner.os }}
       retention-days: 5
       
    - name: Telegram message
      uses: appleboy/telegram-action@master
      with:
        to: 826611050
        token: ${{ secrets.BOT_TGTOKEN }}
        message: |
          Event occured in ${{ github.repository }} repository by ${{ github.actor }}.
          Event type: ${{ github.event_name }}
          Event status: ${{ job.status }}
        document: ${{ env.app_name }}_${{ runner.os }}
